# Generated by Django 4.1.7 on 2023-03-02 14:27

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the numbers must be after the letters, and the allowed characters are between 6 and 30', regex='^[a-zA-Z][a-zA-Z0-9]{5,30}$')])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Your email is not valid', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('mr', 'Man'), ('mrs', 'Female')], max_length=10, verbose_name='Gender (mr/mrs)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
