# Generated by Django 4.1.7 on 2023-03-02 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the numbers must be after the letters, and the allowed characters are between 6 and 30', regex='^[a-zA-Z][a-zA-Z0-9]{6,30}$')])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Your email is not valid', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('mr', 'Man'), ('mrs', 'Female')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('account_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
