# Generated by Django 4.1.7 on 2023-03-02 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed and the numbers must be after the letters', regex='^[a-zA-Z][a-zA-Z0-9]{6,30}$')]),
        ),
    ]
