# Generated by Django 4.1.7 on 2023-03-02 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='The format is not valid\nOnly English letters and numbers are allowed', regex='^[a-zA-Z]{2,30}$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='The format is not valid\nOnly English letters and numbers are allowed', regex='^[a-zA-Z]{2,30}$')], verbose_name='last name'),
        ),
    ]
