# Generated by Django 4.1.7 on 2023-03-02 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the allowed characters are between 2 and 30', regex='^[a-zA-Z]{2,30}$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only English letters and numbers are allowed, and the numbers must be after the letters, and the allowed characters are between 6 and 30', regex='^[a-zA-Z][a-zA-Z0-9]{6,30}$')]),
        ),
    ]
